/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/objects/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Objects by Type */
        get: operations["listObjects"];
        put?: never;
        /** Post Objects */
        post: operations["createObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{type}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Objects List */
        get: operations["listObjectsExplicit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{type}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Objects by Type */
        get: operations["searchObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Objects by Type and ID */
        get: operations["getObject"];
        /** Update Objects */
        put: operations["replaceObject"];
        post?: never;
        /** Delete Objects */
        delete: operations["deleteObject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AUTH */
        get: operations["getPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Views (role-aware) */
        get: operations["listViews"];
        put?: never;
        /** Create a View */
        post: operations["createView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a View */
        get: operations["getView"];
        /** Replace a View */
        put: operations["replaceView"];
        post?: never;
        /** Delete a View */
        delete: operations["deleteView"];
        options?: never;
        head?: never;
        /** Update a View (partial) */
        patch: operations["updateView"];
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces (role-aware) */
        get: operations["listWorkspaces"];
        put?: never;
        /** Create a Workspace */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Workspace */
        get: operations["getWorkspace"];
        /** Replace a Workspace */
        put: operations["replaceWorkspace"];
        post?: never;
        /** Delete a Workspace */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        /** Update a Workspace (partial) */
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/inventory/{id}/onhand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get computed on-hand for an inventory item */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description On-hand computed for the inventory item */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["InventoryOnHand"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/onhand:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch on-hand query */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["InventoryOnHand"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List movements for an inventory item */
        get: {
            parameters: {
                query?: {
                    next?: string | null;
                    limit?: number;
                    sort?: "asc" | "desc";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged list of inventory movements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListPageInventoryMovement"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{id}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust on-hand (creates movement) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InventoryAdjustmentRequest"];
                };
            };
            responses: {
                /** @description Adjustment recorded as an inventory movement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryMovement"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchasing/po/{id}:submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit purchase order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchasing/po/{id}:approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve purchase order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchasing/po/{id}:receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive against purchase order lines */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @deprecated */
                        idempotencyKey?: string;
                        lines?: {
                            lineId: string;
                            deltaQty: number;
                            locationId?: string;
                            lot?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchasing/po/{id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel purchase order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchasing/po/{id}:close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close purchase order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-orders/{id}/receive-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive a specific PO line */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lineId: string;
                        qty: number;
                        lot?: string | null;
                        location?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/so/{id}:submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit sales order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/so/{id}:commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit/allocate inventory for a sales order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/so/{id}:fulfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fulfill items on a sales order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @deprecated */
                        idempotencyKey?: string;
                        lines?: {
                            lineId: string;
                            /** @description Quantity shipped/picked (positive) */
                            deltaQty: number;
                            locationId?: string;
                            lot?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/so/{id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel sales order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/so/{id}:close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close sales order */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales-orders/{id}/fulfill-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fulfill a specific SO line */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lineId: string;
                        qty: number;
                        lot?: string | null;
                        location?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesOrder"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/registration/{id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a registration */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated registration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Registration"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/registration/{id}:checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check in a registration */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated registration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Registration"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/registration/{id}:checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check out a registration */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated registration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Registration"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/reservation/{id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a reservation */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated reservation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/reservation/{id}:start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a reservation (resource now in use) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated reservation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/reservation/{id}:end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End a reservation (resource returned) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional idempotency key for safe retries. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated reservation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reservation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Audit */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ObjectBase: {
            id: string;
            tenantId: string;
            type?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        AnyObject: {
            [key: string]: unknown;
        };
        View: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "view";
            /** @description e.g., products, inventory, events */
            moduleKey: string;
            name: string;
            queryJSON: {
                [key: string]: unknown;
            };
            ownerId?: string | null;
            shared?: boolean;
            isDefault?: boolean;
        };
        ViewList: {
            items?: components["schemas"]["View"][];
            next?: string | null;
        };
        WorkspaceTile: {
            moduleKey: string;
            viewId?: string | null;
            inlineQuery?: {
                [key: string]: unknown;
            } | null;
            layout?: {
                [key: string]: unknown;
            };
        };
        Workspace: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "workspace";
            name: string;
            tiles: components["schemas"]["WorkspaceTile"][];
            ownerId?: string | null;
            shared?: boolean;
        };
        WorkspaceList: {
            items?: components["schemas"]["Workspace"][];
            next?: string | null;
        };
        Policy: {
            tenantId?: string;
            userId?: string;
            roles: string[];
            permissions: string[];
            ui?: {
                allowedModuleKeys?: string[];
                allowedViews?: {
                    id?: string;
                    moduleKey?: string;
                }[];
                allowedWorkspaces?: {
                    id?: string;
                    name?: string;
                }[];
            };
        };
        Client: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "client";
            name: string;
            displayName?: string;
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
            notes?: string;
        };
        Account: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "account";
            name: string;
            number?: string;
            /** @default USD */
            currency: string;
            /**
             * @description e.g., asset, liability, revenue, expense, equity
             * @enum {string}
             */
            accountType?: "asset" | "liability" | "revenue" | "expense" | "equity";
            /** @description Current balance (display only) */
            readonly balance?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
        };
        Product: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "product";
            name: string;
            /**
             * @default good
             * @enum {string}
             */
            kind: "good" | "service";
            sku?: string;
            price?: number;
            taxCode?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
            notes?: string;
        };
        InventoryItem: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "inventory";
            /** @description Optional link to a product */
            productId?: string;
            name: string;
            sku?: string;
            /**
             * @deprecated
             * @description Deprecated – use /inventory/{id}/onhand
             */
            quantity?: number;
            /** @description Unit of measure */
            uom?: string;
            location?: string;
            minQty?: number;
            maxQty?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
            notes?: string;
        };
        InventoryMovement: {
            id?: string;
            /** @enum {string} */
            type: "inventoryMovement";
            /**
             * Format: date-time
             * @description Event timestamp
             */
            ts: string;
            /**
             * Format: date-time
             * @description Mirror of ts for UI lists
             */
            readonly createdAt?: string;
            /** @description Inventory item id */
            itemId: string;
            /** @description Mirror of itemId for client convenience */
            inventoryId?: string;
            deltaQty: number;
            uom: string;
            locationId?: string | null;
            lot?: string | null;
            /**
             * @description Source document type
             * @enum {string}
             */
            sourceType: "PO" | "SO" | "ADJ";
            /**
             * @description Derived from sourceType
             * @enum {string|null}
             */
            kind?: "receive" | "fulfill" | "adjust" | null;
            sourceId: string;
            lineId?: string | null;
            notes?: string | null;
        };
        InventoryOnHand: {
            id: string;
            qtyOnHand: number;
            qtyAvailable?: number | null;
            /** Format: date-time */
            asOf?: string;
        };
        InventoryAdjustmentRequest: {
            reason: string;
            deltaQty: number;
            notes?: string | null;
        };
        ListPageInventoryMovement: {
            items?: components["schemas"]["InventoryMovement"][];
            next?: string | null;
        };
        Resource: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "resource";
            name: string;
            code?: string;
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        Event: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "event";
            name: string;
            description?: string;
            location?: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
            /**
             * Format: date-time
             * @description Alias of startsAt (deprecated)
             */
            start?: string;
            /**
             * Format: date-time
             * @description Alias of endsAt (deprecated)
             */
            end?: string;
            /**
             * @description Operational availability of the event
             * @default available
             * @enum {string}
             */
            status: "draft" | "scheduled" | "open" | "closed" | "completed" | "cancelled" | "archived";
            capacity?: number;
            notes?: string;
        };
        Registration: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "registration";
            eventId: string;
            clientId: string;
            clientName?: string | null;
            /** @default 1 */
            qty: number;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            endsAt?: string | null;
            /**
             * Format: date-time
             * @description Alias of startsAt (deprecated)
             */
            start?: string | null;
            /**
             * Format: date-time
             * @description Alias of endsAt (deprecated)
             */
            end?: string | null;
            /** Format: date-time */
            registeredAt?: string | null;
            /**
             * @default pending
             * @enum {string}
             */
            status: "pending" | "confirmed" | "checked_in" | "checked_out" | "cancelled";
            notes?: string | null;
        };
        Reservation: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "reservation";
            resourceId: string;
            resourceName?: string;
            eventId?: string | null;
            clientId: string;
            clientName?: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /**
             * Format: date-time
             * @description Alias of startsAt (deprecated)
             */
            start?: string;
            /**
             * Format: date-time
             * @description Alias of endsAt (deprecated)
             */
            end?: string;
            /**
             * @default pending
             * @enum {string}
             */
            status: "pending" | "confirmed" | "in_use" | "checked_in" | "completed" | "cancelled";
            notes?: string | null;
        };
        Vendor: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "vendor";
            name: string;
            displayName?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            notes?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
        };
        Employee: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "employee";
            name: string;
            displayName?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            role?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "terminated";
            /** Format: date-time */
            hiredAt?: string;
            /**
             * Format: date-time
             * @description Alias of hiredAt for UI consistency
             */
            startDate?: string;
            /** Format: date-time */
            terminatedAt?: string;
            notes?: string;
        };
        Organization: components["schemas"]["ObjectBase"] & {
            /**
             * @example organization
             * @enum {string}
             */
            type: "organization";
            /** @example National Dressage Foundation */
            name: string;
            /**
             * @example federation
             * @enum {string}
             */
            kind?: "club" | "federation" | "venueOp" | "sponsor";
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
            notes?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        MoneyTotals: {
            subtotal?: number;
            tax?: number;
            shipping?: number;
            discount?: number;
            total?: number;
        };
        PurchaseOrderLine: {
            id?: string;
            /** @description InventoryItem.id */
            itemId: string;
            productId?: string | null;
            description?: string | null;
            uom: string;
            /** @description Ordered quantity */
            qty: number;
            /** @default 0 */
            qtyReceived: number;
            unitPrice?: number | null;
            taxRate?: number | null;
            lineTotal?: number | null;
            locationId?: string | null;
            lot?: string | null;
            /** Format: date-time */
            expectedDate?: string | null;
        };
        PurchaseOrder: {
            id?: string;
            tenantId?: string;
            /** @enum {string} */
            type: "purchaseOrder";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            metadata?: {
                [key: string]: unknown;
            };
        } & {
            orderNumber?: string;
            vendorId?: string;
            vendorName?: string;
            /** @enum {string} */
            status?: "draft" | "submitted" | "approved" | "partially_received" | "received" | "cancelled";
            /** @default USD */
            currency: string;
            notes?: string;
            totals?: components["schemas"]["MoneyTotals"];
            shipTo?: {
                name?: string;
                address1?: string;
                address2?: string;
                city?: string;
                state?: string;
                postal?: string;
                country?: string;
            };
            billTo?: {
                name?: string;
                address1?: string;
                address2?: string;
                city?: string;
                state?: string;
                postal?: string;
                country?: string;
            };
            lines?: components["schemas"]["PurchaseOrderLine"][];
        };
        SalesOrderLine: {
            id?: string;
            /** @description InventoryItem.id being sold */
            itemId: string;
            productId?: string | null;
            description?: string | null;
            uom: string;
            /** @description Ordered quantity */
            qty: number;
            /** @default 0 */
            qtyFulfilled: number;
            unitPrice?: number | null;
            taxRate?: number | null;
            lineTotal?: number | null;
            locationId?: string | null;
            lot?: string | null;
            /** Format: date-time */
            expectedDate?: string | null;
        };
        SalesOrder: {
            id?: string;
            tenantId?: string;
            /** @enum {string} */
            type: "salesOrder";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            metadata?: {
                [key: string]: unknown;
            };
        } & {
            orderNumber?: string;
            customerId?: string;
            customerName?: string;
            /** @enum {string} */
            status?: "draft" | "submitted" | "committed" | "partially_fulfilled" | "fulfilled" | "cancelled" | "closed";
            /** @default USD */
            currency: string;
            notes?: string;
            totals?: components["schemas"]["MoneyTotals"];
            billTo?: {
                name?: string;
                address1?: string;
                address2?: string;
                city?: string;
                state?: string;
                postal?: string;
                country?: string;
            };
            shipTo?: {
                name?: string;
                address1?: string;
                address2?: string;
                city?: string;
                state?: string;
                postal?: string;
                country?: string;
            };
            lines?: components["schemas"]["SalesOrderLine"][];
        };
        GoodsReceiptLine: {
            lineId: string;
            deltaQty: number;
            locationId?: string | null;
            lot?: string | null;
        };
        GoodsReceipt: {
            id?: string;
            /** @enum {string} */
            type: "goodsReceipt";
            tenantId?: string;
            poId: string;
            userId?: string | null;
            /** Format: date-time */
            ts: string;
            lines: components["schemas"]["GoodsReceiptLine"][];
            notes?: string | null;
            attachments?: string[];
        };
        SalesFulfillmentLine: {
            lineId: string;
            deltaQty: number;
            locationId?: string | null;
            lot?: string | null;
        };
        SalesFulfillment: {
            id?: string;
            /** @enum {string} */
            type: "salesFulfillment";
            tenantId?: string;
            soId: string;
            userId?: string | null;
            /** Format: date-time */
            ts: string;
            lines: components["schemas"]["SalesFulfillmentLine"][];
            carrier?: string | null;
            tracking?: string | null;
            notes?: string | null;
            attachments?: string[];
        };
        Integration: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "integration";
            /** @enum {string} */
            provider: "shopify" | "quickbooks" | "rfid" | "webhook" | "streaming";
            /** @enum {string} */
            status: "disabled" | "enabled";
            config?: {
                [key: string]: unknown;
            };
        };
        IntegrationRun: components["schemas"]["ObjectBase"] & {
            /** @enum {string} */
            type: "integrationRun";
            integrationId: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** @enum {string} */
            status: "queued" | "running" | "success" | "error";
            stats?: {
                [key: string]: unknown;
            };
            error?: string | null;
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                    code?: string;
                    details?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /** @description Paged list of objects */
        ListPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items?: components["schemas"]["AnyObject"][];
                    next?: string | null;
                };
            };
        };
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                };
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description Optional idempotency key for safe retries. */
        IdempotencyKey: string;
        TenantHeader: string;
        TypePath: string;
        IdPath: string;
        Limit: number;
        Next: string;
        Q: string;
        Fields: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listObjects: {
        parameters: {
            query?: {
                q?: components["parameters"]["Q"];
                limit?: components["parameters"]["Limit"];
                next?: components["parameters"]["Next"];
                fields?: components["parameters"]["Fields"];
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                type: components["parameters"]["TypePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListPage"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createObject: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                type: components["parameters"]["TypePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnyObject"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listObjectsExplicit: {
        parameters: {
            query?: {
                q?: components["parameters"]["Q"];
                limit?: components["parameters"]["Limit"];
                next?: components["parameters"]["Next"];
                fields?: components["parameters"]["Fields"];
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                type: components["parameters"]["TypePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListPage"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    searchObjects: {
        parameters: {
            query?: {
                q?: components["parameters"]["Q"];
                limit?: components["parameters"]["Limit"];
                next?: components["parameters"]["Next"];
                fields?: components["parameters"]["Fields"];
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                type: components["parameters"]["TypePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ListPage"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getObject: {
        parameters: {
            query?: {
                fields?: components["parameters"]["Fields"];
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                type: components["parameters"]["TypePath"];
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceObject: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                type: components["parameters"]["TypePath"];
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnyObject"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteObject: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                type: components["parameters"]["TypePath"];
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listViews: {
        parameters: {
            query?: {
                moduleKey?: string;
                ownerId?: string;
                shared?: boolean;
                isDefault?: boolean;
                limit?: components["parameters"]["Limit"];
                next?: components["parameters"]["Next"];
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewList"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createView: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["View"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getView: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceView: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["View"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteView: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateView: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["View"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: {
                ownerId?: string;
                shared?: boolean;
                limit?: components["parameters"]["Limit"];
                next?: components["parameters"]["Next"];
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Workspace"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceWorkspace: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Workspace"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
                /** @description Optional idempotency key for safe retries. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                since?: string;
                limit?: number;
            };
            header: {
                "x-tenant-id": components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
