name: CI Smoke

on:
  push:
    branches: [ main, feat/**, fix/**, hotfix/** ]
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      # Read by ops/smoke.mjs
      MBAPP_API_BASE:   ${{ secrets.MBAPP_API_BASE }}
      MBAPP_TENANT_ID:  ${{ secrets.MBAPP_TENANT_ID }}   # e.g. DemoTenant
      MBAPP_BEARER:     ${{ secrets.MBAPP_BEARER }}      # optional; login will run if empty
      NODE_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Echo target API base (redacted bearer)
        run: |
          echo "API_BASE=$MBAPP_API_BASE"
          if [ -n "$MBAPP_BEARER" ]; then echo "BEARER=(set)"; else echo "BEARER=(not set)"; fi

      - name: Login (dev) if needed
        run: |
          node ops/smoke.mjs env
          node ops/smoke.mjs login --tenant "${MBAPP_TENANT_ID:-DemoTenant}" --email "dev@example.com" --policy full

      - name: Quick sanity (list only)
        run: |
          node ops/smoke.mjs smoke:all:list

      - name: Flows (PO & SO)
        run: |
          node ops/smoke.mjs smoke:purchaseOrder:flow --lines 2 --qty 1
          node ops/smoke.mjs smoke:salesOrder:flow    --lines 2 --qty 1

      # Optional deeper CRUD sweep — uncomment if you want full CRUD in CI
      # - name: CRUD sweep
      #   run: |
      #     node ops/smoke.mjs smoke:all:create --each 1
      #     node ops/smoke.mjs smoke:all:update
      #     node ops/smoke.mjs smoke:all:delete
