name: Spec & Types

on:
  pull_request:
    paths:
      - "spec/**"
      - "apps/api/src/**"
      - ".github/workflows/spec-ci.yml"

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - run: npm ci
      - run: npm ci
      - run: npm run spec:lint
      - run: npm run spec:bundle
      - run: npm run spec:types:api
      - run: npm run spec:types:mobile
      - run: npm run api:build
