name: Spec & Types

on:
  pull_request:
    paths:
      - "spec/**"
      - "apps/api/src/**"
      - "apps/mobile/src/**"
      - ".github/workflows/spec-types.yml"

permissions:
  contents: read

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Lint OpenAPI
        run: npm run spec:lint

      - name: Bundle OpenAPI
        run: npm run spec:bundle

      - name: Generate Types (API)
        run: npm run spec:types:api

      - name: Generate Types (Mobile)
        run: npm run spec:types:mobile

      - name: Build API (sanity)
        run: npm run api:build
